services:

  dante:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dante
    command: sockd-username
    env_file:
      - .env
    ports:
      - "1080:1080"
    volumes:
      - ./sockd.conf:/etc/sockd.conf

